@extends('layouts.admin')
@section('title','Salute indicizzazione')
@section('content')
<div class="admin-topbar"><h1 class="admin-page-title">Salute indicizzazione</h1><a class="btn btn--primary" href="{{ route('admin.search-console-coverage.import-form') }}">+ Importa Coverage</a></div>
@if(session('status'))<p style="padding:.8rem;border:1px solid #99f6e4;background:#f0fdfa;color:#0f766e">{{ session('status') }}</p>@endif
<p style="color:var(--admin-muted);font-size:.85rem">Fotografia read-only da un export manuale Search Console. Non modifica sitemap, canonical, robots, redirect, contenuti o indicizzazione.</p>
@if($selected)
<form method="GET" class="articles-toolbar" style="margin:1rem 0"><div class="articles-toolbar__field"><label class="form-label" for="import">Import</label><select class="form-select" id="import" name="import" onchange="this.form.submit()">@foreach($imports as $import)<option value="{{ $import->id }}" @selected($selected->id === $import->id)>{{ $import->property }} · {{ $import->observed_at->format('d/m/Y') }}</option>@endforeach</select></div><div class="articles-toolbar__field"><label class="form-label" for="classification">Stato</label><select class="form-select" id="classification" name="classification" onchange="this.form.submit()"><option value="">Tutti</option>@foreach(\App\Models\SearchConsoleCoverageIssue::classificationLabels() as $value=>$label)<option value="{{ $value }}" @selected($classification === $value)>{{ $label }}</option>@endforeach</select></div></form>
<p style="font-size:.82rem;color:var(--admin-muted)">Property: <strong>{{ $selected->property }}</strong> · osservazione {{ $selected->observed_at->format('d/m/Y') }} · importato {{ $selected->imported_at->timezone('Europe/Rome')->format('d/m/Y H:i') }}</p>
<div style="overflow-x:auto"><table class="admin-table"><thead><tr><th>Ragione</th><th>Pagine</th><th>Stato</th><th>URL</th><th>Audit locale</th><th>Azione consigliata</th></tr></thead><tbody>@forelse($issues as $issue)<tr><td>{{ $issue->reason }}</td><td>{{ number_format($issue->page_count) }}</td><td>{{ \App\Models\SearchConsoleCoverageIssue::classificationLabels()[$issue->classification] }}</td><td>@if($issue->page_url)<a href="{{ $issue->page_url }}" target="_blank" rel="noopener noreferrer">{{ \Illuminate\Support\Str::limit($issue->page_url, 45) }}</a>@else — @endif</td><td>@if($issue->audit)<small>HTTP {{ $issue->audit['http_status'] ?? '—' }} · sitemap: {{ ($issue->audit['in_sitemap'] ?? null) === true ? 'sì' : (($issue->audit['in_sitemap'] ?? null) === false ? 'no' : 'n/d') }}<br>canonical: {{ $issue->audit['canonical'] ?: '—' }}<br>robots: {{ $issue->audit['robots'] ?: '—' }}</small>@else — @endif</td><td style="max-width:380px">{{ $issue->recommendation }}</td></tr>@empty<tr><td colspan="6">Nessuna riga per questo filtro.</td></tr>@endforelse</tbody></table></div>
@else
<div class="articles-empty-state"><p>Nessun export Coverage importato.</p><p class="articles-empty-state__hint">Importa un CSV privato da Google Search Console. Il file non viene committato nel repository.</p></div>
@endif
@endsection
