@extends('layouts.admin')
@section('title','Decisioni editoriali SEO')
@section('content')
<div class="admin-topbar"><h1 class="admin-page-title">Decisioni editoriali SEO</h1></div>
<p style="color:var(--admin-muted);font-size:.85rem;max-width:82ch">Coda read-only basata su opportunità Search Console già importate e sulla readiness organica. Le azioni sono suggerimenti per la redazione: non modificano contenuti, collegamenti, sitemap, canonical o stato di pubblicazione e non garantiscono un ranking.</p>
<form method="GET" class="articles-toolbar" style="margin:1rem 0">
  <div class="articles-toolbar__field"><label class="form-label" for="period">Periodo</label><select id="period" name="period" class="form-select" onchange="this.form.submit()">@foreach($periods as $period)<option value="{{ $period['period_start'] }}|{{ $period['period_end'] }}" @selected($selected && $selected['period_start']===$period['period_start'] && $selected['period_end']===$period['period_end'])>{{ \Illuminate\Support\Carbon::parse($period['period_start'])->format('d/m/Y') }} – {{ \Illuminate\Support\Carbon::parse($period['period_end'])->format('d/m/Y') }}</option>@endforeach</select></div>
  <div class="articles-toolbar__field"><label class="form-label" for="decision">Decisione</label><select id="decision" name="decision" class="form-select" onchange="this.form.submit()"><option value="">Tutte</option>@foreach(\App\Services\OrganicDiscovery\EditorialOpportunityDecisionService::labels() as $value=>$label)<option value="{{ $value }}" @selected($decision===$value)>{{ $label }}</option>@endforeach</select></div>
</form>
@if($selected)
<dl style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:.75rem;margin:1rem 0">@foreach(\App\Services\OrganicDiscovery\EditorialOpportunityDecisionService::labels() as $state=>$label)<div class="admin-card" style="margin:0"><dt style="font-size:.7rem;color:var(--admin-muted)">{{ $label }}</dt><dd style="font-size:1.3rem;margin:.2rem 0 0">{{ $counts[$state] ?? 0 }}</dd></div>@endforeach</dl>
@if($rows->isEmpty())<div class="articles-empty-state"><p>Nessuna decisione per questo filtro.</p></div>@else
<div style="overflow-x:auto"><table class="admin-table"><thead><tr><th>Decisione</th><th>Query / evidenza</th><th>Articolo</th><th>Readiness</th><th>Motivazione e azione</th></tr></thead><tbody>@foreach($rows as $row)<tr><td><strong>{{ $row['decision_label'] }}</strong></td><td><strong>{{ $row['query'] }}</strong><br><small>{{ $row['impressions'] }} impression · {{ $row['ctr'] !== null ? number_format($row['ctr']*100,1).'%' : 'CTR n/d' }} · posizione {{ $row['position'] ?? 'n/d' }}</small></td><td>@if($row['article'])<a href="{{ route('admin.articles.edit',$row['article']) }}">{{ \Illuminate\Support\Str::limit($row['article']->title,48) }}</a><br><small><a href="{{ route('admin.organic-discovery-readiness.show',$row['article']) }}">Ricerca organica</a> · <a href="{{ route('admin.internal-link-audit') }}">Link interni</a></small>@else — @endif</td><td>{{ $row['readiness']['state_label'] ?? 'n/d' }}</td><td style="max-width:380px">{{ $row['reason'] }}<br><small style="color:var(--admin-muted)"><strong>Azione:</strong> {{ $row['action'] }}</small>@if($row['possible_collision_article_ids']!==[])<br><small>Possibile collisione: articoli #{{ implode(', #',$row['possible_collision_article_ids']) }}</small>@endif</td></tr>@endforeach</tbody></table></div>@endif
@else <div class="articles-empty-state"><p>Nessun import Search Console disponibile.</p><p><a href="{{ route('admin.search-opportunities.import-form') }}">Importa un CSV</a> per generare decisioni.</p></div>@endif
@endsection
